# Site settings
course_name: Analogue Electronics
course_description: "This course builds on the knowledge acquired in previous courses to provide the students with an understanding of the working principles of analog electronic devices and circuits. It covers diodes, rectifiers, and power supplies, transistors, special electronic devices and applications, single-stage and multistage amplifiers, differential and tuned Amplifiers, feedback amplifiers, and oscillators.
The course is designed to teach theoretical foundations of analog circuit design through immersion in best practices in circuit design, analysis, and simulation. Each chapter will be accompanied by lecture sessions, laboratory experiments, and detailed worked examples that provides a step-by-step solution to a given problem. The goals of the laboratory experiments are to help the students develop practical skills and to reinforce topics covered in the lectures."
course_semester: 
course_semester: "2022: Trimester I"

baseurl: "/epe2165" # the subpath of your site, e.g. /blog/
url: "https://qiriro.com" # the base hostname & protocol for your site

schoolname: ""
schoolurl: "https://qiriro.com"

twitter_username: nkuzito 

address: |
    Kizito NKURIKIYEYEZU, Ph.D.
    http://qiriro.com

# Set your Google Analytics tracking ID (set up yours at http://www.google.com/analytics/)
# google_analytics: UA-XXXXXXXX-X
google_analytics: UA-255547804

### Do not change the followings unless you know what you are doing ###

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['develop']

dateformat: "%m/%d/%Y"

future: true
collections:
    events:
        output: true
    lectures:
        output: true
    assignments:
        output: true
    announcements:
        output: false


defaults:
  - scope:
      path: ""
      type: "assignments"
    values:
      layout: "assignment"
